### ISSUE TITLE
[Bug Report] uses a placeholder - free composite type of input box position misplacement in the form

### ISSUE THREAD

**Issue by ch940150534** [ElemeFE/element#10188]
### Element UI version
2.2.2

### OS/Browsers version
Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/674/](https://jsfiddle.net/mmx38qxw/674/)

### Steps to reproduce
在表单中使用无placeholder的复合型输入框

### What is Expected?
label与input对齐

### What is actually happening?
label与input发生错位，input乡下偏移10px

**Comment by Leopoldthecoder** [comment]
在 #10189 修复。暂时可以自己加一下这个样式：
```css
.el-form-item__content .el-input-group {
  vertical-align: middle;
}
```
https://jsfiddle.net/mmx38qxw/687/
