### ISSUE TITLE
[Bug Report] el-table组件在imac 4k屏safari浏览器显示异常

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#10308]
### Element UI version
2.2.0

### OS/Browsers version
Mac OXS / safari

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/0wnt3tou/](https://jsfiddle.net/0wnt3tou/)

### Steps to reproduce
设置 css内容为 
```css
@import url("//unpkg.com/element-ui/lib/theme-chalk/index.css");
#app .el-table .el-table__body td .cell {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

### What is Expected?
表头与表内容表内容列对齐，并且设置了 `show-overflow-tooltip` 的单元格超出的内容以省略号显示。

### What is actually happening?
表头与表内容表内容列没有对齐，并且设置了 `show-overflow-tooltip` 的单元格当内容过长没有被隐藏。

**Comment by Leopoldthecoder** [comment]
> 并且设置了 show-overflow-tooltip 的单元格当内容过长没有被隐藏

例子中只有第二列设置了 `show-overflow-tooltip` ，你这里说的没有被隐藏指的是哪几列？

**Comment by fengyun2** [comment]
@Leopoldthecoder 所有列（只要内容超出了自动分配的宽度）。
并且设置了

```css
#app .el-table .el-table__body td .cell {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
