### ISSUE TITLE
[Bug Report] el-table components display exceptions on IMAC 4K screen Safari browsers

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#10309]
### Element UI version
2.2.0

### OS/Browsers version
Mac OXS / safari

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/0wnt3tou/](https://jsfiddle.net/0wnt3tou/)

### Steps to reproduce
设置 css内容为 
```css
@import url("//unpkg.com/element-ui/lib/theme-chalk/index.css");
#app .el-table .el-table__body td .cell {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

### What is Expected?
表头与表内容表内容列对齐，并且设置了 `show-overflow-tooltip` 的单元格超出的内容以省略号显示。
![image](https://user-images.githubusercontent.com/8147202/37759852-d3b5a6f0-2def-11e8-8843-eff8135022fc.png)

### What is actually happening?
表头与表内容表内容列没有对齐，并且设置了 `show-overflow-tooltip` 的单元格当内容过长没有被隐藏。
