### ISSUE TITLE
目前使用过程中的几点建议与反馈

### ISSUE THREAD

**Issue by chenkby** [ElemeFE/element#1043]
１、table的hover问题。前面有人提过这个问题https://github.com/ElemeFE/element/issues/996 ，发现inline-template也会不断执行。这个问题比较影响性能。
２、inline-template目前好像无法获取prop值？比如我想简单地对table进行封装，加上一些底部工具条之类的，此时的prop可能是动态的，能够获取的话好一点。
３、pagination的自定义文本。比如上一页、下一页可能想要文本显示，而不是目前的箭头图标。
４、dropdown在打开状态时给父节点添加一个open的css class，比较好控制打开时的外观。
５、dropdown打开后的内容区也是一样，现在是全局的el-dropdown-menu，有时候2个不同区域的dropdown可能需要外观不一样，能自义个css class会灵活些。

**Comment by QingWei-Li** [comment]
2. 后续可以在 inline-template 里获取 `prop`
3. 目前的设计只有图标的形式，如果想改成文字的话，可以覆盖图标样式
```css
.el-icon-arrow-left:before {
    content: "上一页";
}
.el-icon-arrow-right:before {
    content: "下一页";
}
```
