### ISSUE TITLE
[Feature Request] Automatic column width adjustment

### ISSUE THREAD

**Issue by tsypa** [ElemeFE/element#10969]
### Existing Component
Yes

### Component Name
table

### Description
I's possible to automatic columns width adjustment according to text length?

**Comment by davidrunger** [comment]
@tsypa Does overriding the `table-layout` CSS property accomplish what you want?

```css
.el-table__body, .el-table__footer, .el-table__header {
  table-layout: auto;
}
```

(The default is `table-layout: fixed`.)
