### ISSUE TITLE
[Feature Request] don't invoker input click in component Upload

### ISSUE THREAD

**Issue by falstack** [ElemeFE/element#11246]
### Existing Component
是

### Component Name
Upload

### Description
``` javascript
// upload.vue
handleClick() {
  if (!this.disabled) {
    this.$refs.input.value = null;
    this.$refs.input.click();
  }
},
```

don't do this, it not working on iOS safari

``` scss
.el-upload {
  position: relative;

  .el-upload__input {
    display: block !important;
    opacity: 0;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
  }
}
```

if disabled = true, file[type=input].display = none
