### ISSUE TITLE
[Bug Report] Crash with EDGE when user select el-select many times

### ISSUE THREAD

**Issue by heewook-son** [ElemeFE/element#11629]
### Element UI version
2.4.1

### OS/Browsers version
W10 64bit / Microsoft Edge 42.17134.1.0

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2286/](https://jsfiddle.net/mmx38qxw/2286/)

### Steps to reproduce

1. open element release page (http://element.eleme.io/#/en-US/component/select ) with Edge
2. try to select el-select box many times
3. As you see the below link, you can see edge was killed
https://drive.google.com/file/d/1rbh_78DAPJBo2eoEqip3H2iERM0xE3nw/view?usp=sharing

### What is Expected?
it is working well.

### What is actually happening?
Edge was killed
I tried to this issue with chrome, however it does not reproduce.

**Comment by badpunman** [comment]
Couldn't reproduce on my edge

**Comment by ziyoung** [comment]
Is this related to the operating system language?

**Comment by ziyoung** [comment]
@liuhuaxia 系统版本以及浏览器版本？

**Comment by liuhuaxia** [comment]
@win10，企业版edge浏览器，IE11是正常的官网select频繁点几下就会卡死 @ziyoung

**Comment by liuhuaxia** [comment]
Microsoft Edge 42.17134.1.0 @ziyoung

**Comment by liuhuaxia** [comment]
CSS关闭动画就可以了

**Comment by yakovenkoroman1993** [comment]
I could reproduce this issue

**Comment by yakovenkoroman1993** [comment]
My workaround:
```js
<template>
    <el-select
        @visible-change="visibleChange"
        ...
    >
        /// options
    </el-select>
</template>

<script>
    export default {
        methods: {
            visibleChange(isVisible) {
                const isEdge = window.navigator.userAgent.includes('Edge');
                if (isEdge && !isVisible) {
                    document
                        .querySelectorAll('body > .el-select-dropdown.el-popper')
                        .forEach((it) => it.remove());
                }
            },
        },
    }
</script>
```

**Comment by badpunman** [comment]
Yeah, this reproduced on my home computer with win10 and latest edge. This seems to be a strange bug that affects some systems/edges and not others. 

The above workaround, if it works, is a bit wieldy to implement everywhere. Should be fixed within element.

**Comment by chen00jian** [comment]
> 闭动画就可以了

如何关闭？请准确点

**Comment by karamvirs** [comment]
Any update on this bug.
The issue exists on the element UI documentation page as well.
If you click on the select component a few times the page crashes in Edge.
[element-ui-edge-bug.zip](https://github.com/ElemeFE/element/files/2955175/element-ui-edge-bug.zip)

**Comment by badpunman** [comment]
> Any update on this bug.
nope.

But thankfully edge will eventually move to chromium under the hood so this will eventually get resolved. Just as planned.

**Comment by xiekun1992** [comment]
CSS关闭动画可以的，我是这么做的
```css
.el-zoom-in-bottom-enter-active,.el-zoom-in-bottom-leave-active,.el-zoom-in-left-enter-active,.el-zoom-in-left-leave-active,.el-zoom-in-top-enter-active,.el-zoom-in-top-leave-active
{
  transition: none !important;
  -webkit-transition: none !important;
  -moz-transition: none !important;
  -ms-transition: none !important;
  -o-transition: none !important;
}
```
