### ISSUE TITLE
[Bug Report] table with status el-table :row-class-name="tableRowClassName" does not work on table with stripe

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#11728]
### Element UI version
2.4.1

### OS/Browsers version
macos google chrome 67.0.3396.87

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/zwmcaydn/1/](https://jsfiddle.net/zwmcaydn/1/)

### Steps to reproduce
just run the jsfiddle code

### What is Expected?
rows rowIndex to have green and yellow colors

### What is actually happening?
el-table stripe takes preference over table row status

**Comment by jikkai** [comment]
I create a [PR](https://github.com/ElemeFE/element/pull/11739) to reduce the priority of stripe class, but the CSS which you write in jsfiddle still need to be modified.

```css
.el-table .warning-row td {
  background: oldlace;
}

.el-table .success-row td {
  background: #f0f9eb;
}
```
