### ISSUE TITLE
[Bug Report] select component, multi select mode under IE10, if tag is too much, no line change.

### ISSUE THREAD

**Issue by see311** [ElemeFE/element#12128]
### Element UI version
2.4.4

### OS/Browsers version
WIN10/IE10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/93atrm0s/](https://jsfiddle.net/93atrm0s/)

### Steps to reproduce
在IE10下打开重现链接，选择全部选项，tag如果过多不会换行

### What is Expected?
IE10下多选正常换行显示

### What is actually happening?
IE10下tag如果过多不会换行

**Comment by see311** [comment]
```css
.el-select .el-select__tags > span {
  display: inline-block;
  width: 100%;
}
```
添加上面的css可解决
