### ISSUE TITLE
[Feature Request] Disable tree transition or render only visible part

### ISSUE THREAD

**Issue by LastImmort** [ElemeFE/element#12249]
### Existing Component
Yes

### Component Name
tree

### Description
When last node have ~3k leafs, tree render becomes lagging, so perfect variant is to render only visible part or at least disable js transitions, can it be realised?

**Comment by ziyoung** [comment]
@LastImmort you can disabled transition by CSS.
```css
.collapse-transition {
   transition: none;
}
```
