### ISSUE TITLE
请问Element修改了`packages/input/src/index.vue`代码，不生效？

### ISSUE THREAD

**Issue by qsfty** [ElemeFE/element#1233]
为了让element支持iconfont图标，我修改了input组件源代码,添加了iconfont图标代码，如下所示：

```
<!-- input iconfont图标 -->
<i class="el-input__icon iconfont" :class="[aicon ? 'icon-' + aicon : '']" v-if="aicon" @click="handleIconClick"></i>
```

求解决方案？

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/1054

**Comment by qsfty** [comment]
这个我看了的，首先input里不支持slot的，我用的是iconfont在线链接，不支持编译呢，能告诉怎么修改源码然后生效吗？这个也许只是一个特例，用了element组件两天，部分组件感觉还是有些小bug，能自己修复就不用麻烦你们了，现在关键是如何让修改的代码生效。

请见教。

**Comment by QingWei-Li** [comment]
到 iconfont 上给图标改个前缀，例如我改成 `el-icon-my`

![image](https://cloud.githubusercontent.com/assets/7565692/20461529/f2ddfade-af3b-11e6-9f0a-248cffa10c39.png)


然后不需要改 Element 的源码，只要像 #1054 里提到的那样写一个样式就好了
```css
[class^="el-icon-my"], [class*=" el-icon-my"] {
  font-family:"iconfont" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 0.2px;
  -moz-osx-font-smoothing: grayscale;
}
```

然后用法就是 `icon="my-xxx"`
```html
<el-input icon="my-xxx" />
```
