### ISSUE TITLE
单选框神奇BUG

### ISSUE THREAD

**Issue by fengcms** [ElemeFE/element#1250]
BUG动图
![](http://ww2.sinaimg.cn/large/0060lm7Tgw1f9zsvrlvj2g30gz07gacz.gif)
代码如下：
```html
<table class="edit_table">
          <tr>
            <th>颜色风格</th>
            <td>
              <el-radio class="radio" v-model="form.skin" label="blue">蓝色</el-radio>
              <el-radio class="radio" v-model="form.skin" label="cyan">青色</el-radio>
              <el-radio class="radio" v-model="form.skin" label="gray">灰色</el-radio>
              <el-radio class="radio" v-model="form.skin" label="green">绿色</el-radio>
              <el-radio class="radio" v-model="form.skin" label="orange">橙色</el-radio>
              <el-radio class="radio" v-model="form.skin" label="pink">粉色</el-radio>
            </td>
          </tr>
        </table>
      </div>
```
表格是我自己写的样式，没有特殊情况，在有滚动条的时候，出现了这种状况。因为有特殊需求，没有使用form组件。

**Comment by furybean** [comment]
从一张图上无法推断出什么原因造成的，请提供测试用例。

**Comment by fengcms** [comment]
经过排查，是以下css导致的：

```css
.el-radio__inner.is-checked::after {
    -webkit-transform: translate(-50%,-50%) scale(1);
    transform: translate(-50%,-50%) scale(1);
}
```
