### ISSUE TITLE
[Bug Report] Switch has outline

### ISSUE THREAD

**Issue by fakaka** [ElemeFE/element#12766]
### Element UI version
2.4.6

### OS/Browsers version
windows 10/Chrome 63

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/vsmj012/0rx832uf/1/](https://jsfiddle.net/vsmj012/0rx832uf/1/)

### Steps to reproduce
点击扩展的 value 类型的 Switch 出现边框

### What is Expected?
点击扩展的 value 类型的 Switch 不出现边框

### What is actually happening?
点击扩展的 value 类型的 Switch 出现边框

**Comment by fakaka** [comment]
caused by this css?
``` css
.el-switch__input:focus~.el-switch__core {
    outline: 1px solid #409eff;
}
```
