### ISSUE TITLE
When [Feature Request] tree control is dragged, it is suggested that highlight is more obvious.

### ISSUE THREAD

**Issue by xuzixian** [ElemeFE/element#12792]
### Existing Component
是

### Component Name
el-tree

### Description
拖拽节点时，建议高亮更明显一点，比如inner时，dropNode整个背景高亮；before以及after时，在插入的位置添加横线高亮标识，这样用户体验应该会更好点。谢谢！

**Comment by ziyoung** [comment]
跟这个 #12112 挺像。算是目前的 bug。

**Comment by ziyoung** [comment]
整个节点高亮，你可以通过 CSS 来控制。
```css
.el-tree-node.is-drop-inner > .el-tree-node__content {
  background: some-color;
}
```
