### ISSUE TITLE
[Bug Report] Blue outline on radio with button style on Safari

### ISSUE THREAD

**Issue by bviala** [ElemeFE/element#12811]
### Element UI version
2.4.7

### OS/Browsers version
macOS 10.13.6 / Safari 12.0

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/zep93f2a/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Click on an option. It's more visible on first and last option because of radius.

### What is Expected?
No blue outline after a radio button is selected

### What is actually happening?
Blue outline after a radio button is selected

**Comment by ibufu** [comment]
```css
  &:focus:not(.is-focus):not(:active):not(.is-disabled){ /*获得焦点时 样式提醒*/
    box-shadow: 0 0 2px 2px $--radio-button-checked-border-color;
  }
```
It is a feature.
