### ISSUE TITLE
element-icons.eot 在 chrome 下的加载报错问题

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#1322]
对字体的引用，在 chrome 下会报错如下：

```
Failed to decode downloaded font:
theme-default/fonts/element-icons.eot?t=1472440741
OTS parsing error: invalid version tag
```

演示示例：https://jsfiddle.net/gmve9d3p/85/

![parsing_error](https://cloud.githubusercontent.com/assets/2276421/20584923/fdf84250-b231-11e6-9782-2512cecf5731.png)

### 问题与解决

写法有问题，对 IE 的兼容应该分开来写。对于：

https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/icon.css#L3
```css
@font-face {
    font-family: 'element-icons';
    src:url('fonts/element-icons.eot?t=1472440741'), /* IE9*/
      url('fonts/element-icons.woff?t=1472440741') format('woff'), /* chrome, firefox */
      url('fonts/element-icons.ttf?t=1472440741') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
      url('fonts/element-icons.svg?t=1472440741#el-icon') format('svg'); /* iOS 4.1- */
    font-weight: normal;
    font-style: normal;
}
```

应该这样写：

```css
@font-face {
    font-family: 'element-icons';
    src: url('fonts/element-icons.eot?t=1472440741'); /* IE9*/
    src: url('fonts/element-icons.woff?t=1472440741') format('woff'), /* chrome, firefox */
      url('fonts/element-icons.ttf?t=1472440741') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
      url('fonts/element-icons.svg?t=1472440741#el-icon') format('svg'); /* iOS 4.1- */
    font-weight: normal;
    font-style: normal;
}
```

修改后的示例(不再有报错)： https://jsfiddle.net/gmve9d3p/87/

看了你们官网 webpack 的输出方式，是直接将字体 base64 了，那在浏览器中自然不会有这个问题。
