### ISSUE TITLE
建议 Menu Item Group 内增加 Slot

### ISSUE THREAD

**Issue by saopang** [ElemeFE/element#1334]
### Vue version

在menu的分组前怎么加icon

![image](https://cloud.githubusercontent.com/assets/11707936/20590059/c3a9b2f8-b25b-11e6-89a2-eca2c894f439.png)

需要下面这种效果

![image](https://cloud.githubusercontent.com/assets/11707936/20590064/c9d5c266-b25b-11e6-8630-eeb20a52375e.png)

**Comment by markyun** [comment]
刚好我也在用这个组件，饿了么组件库没有为分组名提供显示图标的功能，你可以这样写试试

`    <el-menu mode="vertical" default-active="1" class="el-menu-vertical-demo">
      <p><i class='el-icon-message'></i>自定义的分组一</p>
      <el-menu-item-group >
        <el-menu-item index="1"><i class="el-icon-message"></i>导航一</el-menu-item>
        <el-menu-item index="2"><i class="el-icon-message"></i>导航二</el-menu-item>
      </el-menu-item-group>
      <el-menu-item-group title="分组二">
        <el-menu-item index="3"><i class="el-icon-message"></i>导航三</el-menu-item>
        <el-menu-item index="4"><i class="el-icon-message"></i>导航四</el-menu-item>
      </el-menu-item-group>
    </el-menu>`

然后自己补充自定义分组的样式即可。

**Comment by saopang** [comment]
@markyun自定义样式暂时解决了。

但希望能预留个接口

```css
.el-menu-item-group__title:before{
    content: "\E614";
    font-family: element-icons!important;
    speak: none;
    font-style: normal;
    font-weight: 400;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    vertical-align: baseline;
    display: inline-block;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    padding-right: 10px;
  }

```
