### ISSUE TITLE
time-spinner 无样式定义问题

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#1335]
导致的效果如图所示：

![time-spinner](https://cloud.githubusercontent.com/assets/2276421/20590254/06cc65de-b25d-11e6-844d-b5898862aafd.png)

查看文档示例，应当添加如下样式修饰：

```css
.el-time-spinner {
    display: flex;
    width: 100%;
}
```
具体位置：https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/date-picker/time-spinner.css#L4

添加后就显示正常了
