### ISSUE TITLE
[Bug Report] el-progress width update issue

### ISSUE THREAD

**Issue by OhAllenGor** [ElemeFE/element#13784]
### Element UI version
2.4.11

### OS/Browsers version
Chrome 71.0.3578.98

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/OhAllenGor/2z1vmejg/5/](https://jsfiddle.net/OhAllenGor/2z1vmejg/5/)

### Steps to reproduce
See above jsfiddle

* * *

_Originally posted by @OhAllenGor in https://github.com/ElemeFE/element/commit/0dce4259d900275860bf773a91c109d6944788ca#commitcomment-31691811_

### What is Expected?
Use above jsfiddle, and Uncomment below css:
```css
.el-progress-bar__inner {
    -webkit-transition: width 0s;
    transition: width 0s;
}
```

### What is actually happening?
The `el-progress` width update not smoothly
