### ISSUE TITLE
使用el-alert控件，文字根图标差距特别大，跟文稿显示不符

### ISSUE THREAD

**Issue by wskaili** [ElemeFE/element#141]
使用如下控件 <el-alert
            title="批量修改后无法撤。。。。"
            type="warning"
            :closable="false"
            show-icon>
          </el-alert>
然后在大屏幕下图标warning跟文字相差64px。查看代码，发现一个奇怪的问题。正确的样式是.el-alert__ico{display:table-cell}然后我本地的样式就是class*=" el-icon-"], [class^=el-icon-] （也是控件里的自带的样式）{display:inline-block}覆盖了.el-alert__ico的样式。请问下这个是什么原因？为什么文稿里就显示正确。我在其他同事电脑上也测试了，效果也是一样的。会相差特别宽。

**Comment by Leopoldthecoder** [comment]
请在浏览器中查看一下 `.el-alert__icon` 这个元素有没有如下样式表：
```css
.el-alert__icon {
  font-size: 16px;
  width: 16px;
  display: table-cell;
  color: #fff;
  vertical-align: middle;
}
```

另外，请使用这个 [模板](https://codepen.io/QingWei-Li/pen/ozYpNA) 看看能否重现问题。
