### ISSUE TITLE
[Feature Request] Move collapse icon to the left

### ISSUE THREAD

**Issue by japhfortin** [ElemeFE/element#14142]
### Existing Component
Yes

### Component Name
collapse

### Description
This is a very simple functionality but I think it would be better if we can have a way to move the arrow icon to the left. On the previous versions (2.2), this can be done very easily with some css tweaks. But I find it hard on version 2.4.1.

**Comment by fengyun2** [comment]
+1

**Comment by Arkhunt** [comment]
+1 
For now I use this css tweak
```
.el-collapse-item__header {
  direction: rtl;
}
```

**Comment by fengyun2** [comment]
看官方怎样修改了
只需要把箭头(el-collapse-item__arrow)移到 el-collapse-item__header的第一个子元素，再调整一下样式就差不多了

```css
.el-collapse-item__arrow {
  margin: 0 8px;
}
.el-collapse-item__content {
   padding-left: 8px;
}
```

![image](https://user-images.githubusercontent.com/8147202/65366455-b6949600-dc56-11e9-8920-0f4e11c5b7ca.png)
