### ISSUE TITLE
[Feature Request] Keep the original ratio of the thumbnails in the upload file list

### ISSUE THREAD

**Issue by xiGUAwanOU** [ElemeFE/element#14410]
### Existing Component
Yes

### Component Name
Upload

### Description
If I choose a file to upload, it will be shown in the preview cards as thumbnails. The current behaviour is the thumbnails will be stretched to fit the 100% width and height. I personally think if there were an option to keep the original ratio of the images, it would be better.

My current temporary solution is:

```css
.image-uploader >>> .el-upload-list__item {
  text-align: center;
  white-space: nowrap;
}

.image-uploader >>> .el-upload-list__item::before {
  content: '';
  display: inline-block;
  width: 0;
  height: 100%;
  vertical-align: middle;
}

.image-uploader >>> .el-upload-list__item-thumbnail {
  max-width: 100%;
  max-height: 100%;
  width: auto;
  height: auto;
  vertical-align: middle;
}
```

Which probably can't be applied to all situations.
