### ISSUE TITLE
progress百分比文字显示自定义述求

### ISSUE THREAD

**Issue by saopang** [ElemeFE/element#1498]
### ElementUI version
1.0.3

### OS/Browers version
Win0/Chrome 53

### Vue version
2.1.3

需要实现的效果：
![image](https://cloud.githubusercontent.com/assets/11707936/20788524/1dce29b8-b7ec-11e6-9ae5-1191a8f7187c.png)

 代码提示：

![image](https://cloud.githubusercontent.com/assets/11707936/20788512/13358d70-b7ec-11e6-9587-93bed09aa5ad.png)

对应的代码：

```css
.el-progress-bar__innerText {
    display: inline-block;
    vertical-align: middle;
    color: #fff;  //这里需要自定义
    font-size: 12px;  //这里需要自定义
    margin: 0 5px;  //这里需要自定义
}
.el-progress-bar__outer {
    height: 6px;
    border-radius: 100px;
    background-color: #e5e9f2;
    overflow: hidden;
    position: relative;
    vertical-align: middle;
}
```

建议修改方案：

设置“el-progress-bar__outer”的overflow属性为visible
"el-progress-bar__innerText"的style属性为progress的一个属性
这样就可以自定义百分比文字的marignTop，font等样式
