### ISSUE TITLE
[Bug Report] Table cannot drag scrollbars with a fixed column position mouse when the height and fixed column are set

### ISSUE THREAD

**Issue by jcbacc** [ElemeFE/element#16907]
### Element UI version
2.11.1

### OS/Browsers version
所有

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/xvPXpL

### Steps to reproduce
在固定列的位置鼠标无法拖动滚动条

### What is Expected?
可以拖动滚动条

### What is actually happening?
无法拖动滚动条

**Comment by xrkffgg** [comment]
兄弟  看这里 https://github.com/ElemeFE/element/pull/16915

你可以先在自己工程里  加上 
```
.el-table--scrollable-x .el-table__body-wrapper {
    z-index : 1;
}
```

**Comment by ziyoung** [comment]
已知问题。

**Comment by 1115332213** [comment]
看了评论 感觉应该使用下面代码， 如果使用 xrkffgg 这个用户的代码 会使得 右fix column 的左边框消失
`.el-table--scrollable-x .el-table__body-wrapper .el-table__body {
  z-index : 1;
}
`

**Comment by shimangdian** [comment]
those way have not help, for me . has other any more way?   >_<

```css
.el-table--scrollable-x .el-table__body-wrapper {
    z-index : 1;
}
```

```css
.el-table--scrollable-x .el-table__body-wrapper .el-table__body { z-index : 1; }
```
