### ISSUE TITLE
[Bug Report] el-drawer does not have a scrollbar

### ISSUE THREAD

**Issue by lalalacampanella** [ElemeFE/element#17713]
### Element UI version
2.12.0

### OS/Browsers version
win10 chrome 74

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mLvkb0f4/

### Steps to reproduce
just create a very long el-drawer, then it comes to have no slider

### What is Expected?
it show's slider as other components

### What is actually happening?
it has no slider

**Comment by tripflex** [comment]
I had to add this CSS to mine to add the scrollbar:

```css
	.el-drawer__body {
		height: 100%;
		box-sizing: border-box;
		overflow-y: auto;
	}
```

Got it from https://github.com/ElemeFE/element/issues/17130#issuecomment-523778100
