### ISSUE TITLE
Loading 组件旋转过程中有碎片

### ISSUE THREAD

**Issue by unknown-coder** [ElemeFE/element#1786]
### ElementUI version

`1.0.6`

### OS/Browers version

`Win10/Chrome 51`

### Vue version

`2.0.7`

### What is Expected?
![image](https://cloud.githubusercontent.com/assets/9328734/21247873/dcba4c94-c36d-11e6-96cf-f62293ee8958.png)

### What is actually happening?
```css
@keyframes dash {
    0% {
        stroke-dasharray: 1, 100;
        stroke-dashoffset: 0
    }
    50% {
        stroke-dasharray: 45, 100;
        stroke-dashoffset: -35px
    }
    100% {
        stroke-dasharray: 45, 100;
        stroke-dashoffset: -124px
    }
}
```

### 说明
`theme-default` 下面, 不管是 `index.css`, 还是 `loading.css`, 里面 `dash` 动画的 `stroke-dasharray` 都与官网上不一致.
