### ISSUE TITLE
官方文档的小问题

### ISSUE THREAD

**Issue by GiorgioPeng** [ElemeFE/element#17932]
[展开行](https://element.eleme.cn/#/zh-CN/component/table#zhan-kai-xing)
中源码样式
```css
  .demo-table-expand {
    font-size: 0;
  }
```
font-size不应该设置为0,否则导致内容无法显示...建议更改.
