### ISSUE TITLE
[Feature Request] a suggestion for mixin the timeline style

### ISSUE THREAD

**Issue by wangtunan** [ElemeFE/element#18038]
### Existing Component
是

### Component Name
timeline

### Description
when I read element source code and write my timeline component today, I do it like this by stylus:
```css
&-small
   left: -1px;
   width: 12px;
   height: 12px;
&-normal
   left: -2px;
   width: 14px
   height: 14px;
&-medium
   left: -3px
   width: 16px;
   height: 16px;
&-large
   left: -4px
   width: 18px;
   height: 18px;
&-primary
   background-color: $base-primary;
&-success
   background-color: $base-success;
&-warning
   background-color: $base-warning;
&-danger
   background-color: $base-danger;
&-info
    background-color: $base-info;
```
and soon I mixin the size and type style like this:
```css
timeline-status($left, $size, $args)
  for size, index in $args
    &-{size}
      left: unit(- ($left   index ), 'px');
      width: unit($size   index * 2, 'px');
      height: @width;

timeline-type($types, $colors)
  for type, index in $types
    &-{type}
      background-color: $colors[index]
```
I use it like this and it is work in my timeline component:
```css
timeline-status(1px, 12px, primary success warning danger info); 
timeline-type(primary success warning danger info, $base-primary $base-success $base-warning $base-danger $base-info);
```
![timeline](https://user-images.githubusercontent.com/48847606/68676118-3e7e8880-0594-11ea-89dc-56f78cefa607.png)

and the style in element timeline component：
```css
@include m(normal) {
  left: -1px;
  width: $--timeline-node-size-normal;
  height: $--timeline-node-size-normal;
}
@include m(large) {
  left: -2px;
  width: $--timeline-node-size-large;
  height: $--timeline-node-size-large;
}

@include m(primary) {
  background-color: $--color-primary;
}
@include m(success) {
  background-color: $--color-success;
}
@include m(warning) {
  background-color: $--color-warning;
}
@include m(danger) {
  background-color: $--color-danger;
}
@include m(info) {
  background-color: $--color-info;
}
```
it’s also can mixin by scss, I hope element timeline component will do like this.
thanks!
