### ISSUE TITLE
Table scroll mofify scrollbar width 

### ISSUE THREAD

**Issue by Mrsbetter** [ElemeFE/element#19215]
### Element UI version
2.13.1

### OS/Browsers version
window10/ chome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mrsbetter/pen/JjYRGzP

### Steps to reproduce
直接打开即可看到

### What is Expected?
gutter宽度，及scroll宽度变小时，不要有默认的16px给滚动条

### What is actually happening?
table的scrollbar宽度变小，表格中的scrollbar宽度撑开的宽度还是16px

**Comment by Criminal-sudo** [comment]
我也出现这种情况，无法修复

**Comment by Criminal-sudo** [comment]
![image](https://user-images.githubusercontent.com/39031006/82125933-cf504e00-97db-11ea-80e3-32e51ded5092.png)

**Comment by zaharr2** [comment]
same problem, no ideas?

**Comment by zaharr2** [comment]
found a solution, use =)))
`.el-scrollbar__wrap::-webkit-scrollbar {
  width: 0;
}`

**Comment by helloCx** [comment]
+1！

**Comment by helloCx** [comment]
> found a solution, use =))) just add this code at main.css
> `.el-scrollbar__wrap::-webkit-scrollbar { width: 0; }`

Good job！

**Comment by Gaays** [comment]
> found a solution, use =))) just add this code at main.css
> `.el-scrollbar__wrap::-webkit-scrollbar { width: 0; }`
add firefox support：
```css
//  webkit
.el-scrollbar__wrap::-webkit-scrollbar {
  width: 0;
}
//  Firefox
.el-scrollbar__wrap {
  scrollbar-width: none;
}
```
