### ISSUE TITLE
[Bug Report] about el-form  z-index question

### ISSUE THREAD

**Issue by zhoufanglu** [ElemeFE/element#21854]
### Element UI version
2.15.8

### OS/Browsers version
111

### Vue version
2.6.14

### Steps to reproduce
```css
.header{
    position: fixed;
    top: 0;
}
```

### What is Expected?
el-form不会覆盖t顶部
![vqTWFZX1hU](https://user-images.githubusercontent.com/24451091/167280187-24f200de-c11e-4763-b34f-8bdd190311ee.gif)

### What is actually happening?
el-form覆盖了顶部
