### ISSUE TITLE
[Feature Request] DateTimePicker 日期时间区间选择器当clearable为false时,能否让弹出层的清空按钮隐藏掉

### ISSUE THREAD

**Issue by ll60** [ElemeFE/element#22213]
### Existing Component
是

### Component Name
DateTimePicker

### Description
当DateTimePicker 日期时间区间选择器当clearable为false时,说明我不想要用户清空输入框，但日历右下角的确认旁边还有个【清空】按钮，是否也应该要隐藏掉？不然clearable为false毫无意义。

![image](https://user-images.githubusercontent.com/30487969/197751138-657b1c53-654d-4cd2-b45c-71785ac652ff.png)

**Comment by gavanx** [comment]
我也遇到这个问题，我理解clearable为false的时候就应该同步没有清空按钮嘛！
先临时解了下项目中的问题
```scss
.my-date-picker-control {
  .el-picker-panel__footer {
    .el-picker-panel__link-btn:nth-child(1){
      display: none;
    }
  }
}
```
