### ISSUE TITLE
el-select 默认样式问题

### ISSUE THREAD

**Issue by k55k32** [ElemeFE/element#2240]
el-select的宽度不随父容器自动扩充
[http://jsfiddle.net/mgw28h1w/](http://jsfiddle.net/mgw28h1w/)

这个是bug还是 调整成这样的? 
之前会跟随父容器的宽度，现在最大宽度好像固定了。
```css
.el-form-item{
  .el-select{
    width: 100%;
  }
}
```
我在自己项目中暂时加上了这样的样式解决了这个问题，不知道会不会有其他影响
