### ISSUE TITLE
Dialog内select tree等组件在点击箭头时有虚晃

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#2461]
### Broswer
Chrome

### Reproduction Link
直接看官网 http://element.eleme.io/#/zh-CN/component/dialog#zi-ding-yi-nei-rong

### Steps to reproduce
点击【嵌套表单的Dialog】，重复点击select

### What is actually happening?
可以看到Dialog有1px的晃动，导致页面模糊

**Comment by Leopoldthecoder** [comment]
Windows 上才有？试试把 `.el-input__icon` 的 width 改成 36px 能不能解决问题，可以的话我就这么改。

**Comment by erguotou520** [comment]
我测试了下几个同事的机子，都是windows的，有1个能重现，1个不能重现...... 我这次改css发现已经不起作用了......

**Comment by erguotou520** [comment]
然后我试了下换掉iconfont，改用css实现，大致代码如下
```css
.el-input__icon {
    position: absolute;
    right: 0;
    width: 36px;
    height: 36px;
}
.el-input__icon::before {
    content: '';
    display: block;
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 8px;
    border-color: #999 transparent transparent transparent;
    top: 14px;
    left: 10px;
}
```
这个是改动之前的效果
![before](https://cloud.githubusercontent.com/assets/7945757/22011243/f99dc970-dcc8-11e6-8cef-610d893e1a5f.gif)
这个是改过之后的
![after](https://cloud.githubusercontent.com/assets/7945757/22011253/021d63e4-dcc9-11e6-83fb-a7f9f74a1b1e.gif)
