### ISSUE TITLE
table固定高度后，出现横向滚动条的问题

### ISSUE THREAD

**Issue by Alisonshaper** [ElemeFE/element#2643]
table组件，设置height后，超过设置高度出现纵向滚动条，但是同时出现横向滚动条。但我希望只出现纵向滚动条。

**Comment by xiongsongsong** [comment]
是不是还使用了bootstrap？

如果是，添加这一段样式：
```css
.el-table table {
  border: none !important;
}
```
