### ISSUE TITLE
所有的时间选择器ui都有点小问题

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2703]
![image](https://cloud.githubusercontent.com/assets/8121621/22677658/5b79d88e-ed2f-11e6-985e-3b015d55fced.png)
如图 

1. 蓝底里的数字没居中
2.hover时，滚轴错位了

**Comment by gemwuu** [comment]
同样遇到这个问题，你可以在 css 中加入如下代码来修复这个问题。
```css
.el-time-panel__content::after, .el-time-panel__content::before {
  margin-top: -8px !important;
}
```
