### ISSUE TITLE
关于tree里面overflow的问题

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#2745]
![qq 20170209101020](https://cloud.githubusercontent.com/assets/16487810/22766346/e4f41170-eeaf-11e6-844e-34cf3eadf9bc.png)
图片右边的操作 按钮被遮住了，
示例demo地址http://jsfiddle.net/k599kg67/
demo里面的文字也是显示不全，我该如何实现这种滚动条效果

**Comment by Leopoldthecoder** [comment]
自己加一条样式：
```css
.el-tree-node__content {
  overflow: auto;
}
```
