### ISSUE TITLE
tabs在默认type时，初始选中标识位置不正确

### ISSUE THREAD

**Issue by terranc** [ElemeFE/element#3221]
### ElementUI version
1.2.3

如图。应该是选中第二个pane，而结果是在中间的位置，我是自定义了样式：
```less
.el-tabs__nav {
      display: flex;
      float: none;

      .el-tabs__item{
        flex:1;
     }
}
```
![image](https://cloud.githubusercontent.com/assets/224353/23514342/0024dc88-ffa2-11e6-8fad-70a3b75727f0.png)
