### ISSUE TITLE
讨论：select remote  filterable，非multiple每次点击输入框都会清空数据这是个feature还是bug？

### ISSUE THREAD

**Issue by acelan86** [ElemeFE/element#422]
### ElementUI version
1.0.0-rc.6

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.1

### Steps to reproduce
```html
<el-select
      v-model="value9"
      filterable
      remote
      placeholder="请输入关键词"
      :remote-method="remoteMethod"
      :loading="loading">
      <el-option
        v-for="item in options4"
        :key="item.value"
        :label="item.label"
        :value="item.value">
      </el-option>
    </el-select>
```
官网例子把multiple去掉
### What is Expected?
感觉不应该清空，而是应该保留上次选择
### What is actually happening?
点击input就清空了

============
更新：看代码好像就是feature，但是大神们，我觉得这个可以讨论下？

**Comment by acelan86** [comment]
另外一个样式问题，select设置长点，会发现第一个选项颜色一半深一半浅，修改方案：
```css

.el-select-dropdown__list {
  list-style: none;
  padding: 6px 0;
  margin: 0;
  width: 100%;
  max-height: 274px;
  box-sizing: border-box;
  overflow-y: auto;
  position: relative  // 这句应该加载这里 __list上，源码中加在了__item上了
}

```
