### ISSUE TITLE
[Feature Request] Remove row-hover hightlight

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#4321]
### Existing Component
Yes

### Component Name
Table

### Description
In tables, when hovering over rows, they are automatically highlighted (it's a grey highlight). Specifically this is controlling the hover:

.el-table--enable-row-hover .el-table__body tr:hover>td

It would be nice if we could turn this off.

**Comment by syn-zeta** [comment]
You could perhaps try using one of these table attributes to override the `tr` hover styling:

![image](https://cloud.githubusercontent.com/assets/26761352/25203446/28b527de-250e-11e7-87e0-63dd7d190034.png)

**Comment by hxlniada** [comment]
@syn-zeta 这样其实不太方便，有时候就是想去掉hover，却需要再加一个class，而且说实话这个hover效果要去掉还得这个样式层级得弄很多才行，不然不够覆盖掉原有样式

**Comment by hxlniada** [comment]
看了一圈issue感觉作者自己都不太用自己写的组件，有些非常常用的应用场景居然完全不理解，而且非常怕添加新功能

**Comment by justintilson** [comment]
The table attribute (_row-class-name_ and _row-style suggestions_) above do not work to override the hover functionality.

**Comment by syn-zeta** [comment]
@hxlniada @justintilson https://jsfiddle.net/x6pz0yhr/

**Comment by justintilson** [comment]
@syn-zeta nice solution! way better than mine. thx.

**Comment by yozian** [comment]
Here is a solution, even if you have fixed columns.

Just override the css class effect in your component .

``` css
.hover-row > td {
  background-color: initial !important;
}
```

**Comment by icoom** [comment]
正解 @yozian

**Comment by gfernandez-me** [comment]
> Here is a solution, even if you have fixed columns.
> 
> Just override the css class effect in your component .
> 
> ```css
> .hover-row > td {
>   background-color: initial !important;
> }
> ```

Awesome

**Comment by davestewart** [comment]
It seems there is a class baked into the table...

https://github.com/ElemeFE/element/blob/dev/packages/table/src/table.vue#L12

...which triggers the hover effect in the compiled CSS:

```scss
.el-table--enable-row-hover .el-table__body tr:hover > td {
  background-color: #f5f7fa;
}
```

However, note that:

- the hover effect is on the `td`, not the `tr` 
- so the trick is to disable that, then override the `tr`:

```scss
// overrides to prevent built-in table row hovering
.el-table--enable-row-hover .el-table__body tr:hover > td {
  background-color: unset;
}

// add table stripes
.el-table__row:nth-child(2n - 1) {
  background: $grey-lightest;
}
```

Hope that helps.
