### ISSUE TITLE
[Feature Request] 表格的 shot-overflow-tooltip 是否可以设置最大宽度

### ISSUE THREAD

**Issue by AnyGong** [ElemeFE/element#4325]
### Existing Component
是

### Component Name
el-table

### Description
实际的表格中可能会存在 show-overflow-tooltip 的内容很长，导致显示的时候，宽度是整屏的情况。所以希望能设置tooltip的最大宽度，可以是整个表格设置或者单列设置。另外就是我这种情况有什么好的解决方案吗？
eg：http://jsfiddle.net/rmpj2zhf/1/

**Comment by scscms** [comment]
添加css样式
```
.el-tooltip__popper{max-width:80%} /*自己选择*/
```

**Comment by jwenjian** [comment]
在vue组件中, 使用scoped style设置css, **无效**:
```css
<style scoped>
.el-tooltip__popper {
  max-width: 200px
}
</style>
```
