### ISSUE TITLE
[Bug Report] 当有一列是fixed时，table显示错位

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#4976]
### Element UI version
1.3.3

### OS/Browsers version
mac os sierra/chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/dqjsk1y2/](https://jsfiddle.net/dqjsk1y2/)

### Steps to reproduce
https://jsfiddle.net/dqjsk1y2/

往下拉滚动条，到后面的数据，表格上下会有错位

### What is Expected?
表格每行都对齐

### What is actually happening?
往下拉滚动条，到后面的数据，表格上下会有错位

![](https://raw.githubusercontent.com/ivan403704409/bug-img/master/element-ui-table-bug1.png)

**Comment by SimGenius** [comment]
而且有时候列神奇的就第一列到最后去了

**Comment by lifanlingjue** [comment]
我也遇到这个问题了。。。 在线等 挺急的。

**Comment by weihongming** [comment]
我也遇到了，很急！！

**Comment by Leopoldthecoder** [comment]
@liril-net Any thoughts? (To reproduce this, remember to switch `show scroll bar` to `always` in system configuration)

**Comment by mcdongWang** [comment]
同一样遇到了问题 需要提供什么信息么?

**Comment by mcdongWang** [comment]
没人来处理这个问题么? @Leopoldthecoder

**Comment by liril-net** [comment]
@mcdongWang 在找一个不会影响到其它功能的解决方案

**Comment by mcdongWang** [comment]
在 横向 和 纵向滚动条都存在的时候  是否使用鼠标 会 影响 fixed的列头 对滚动高度的判断.

我们大量使用了table组价 而且内容都比较多 所以同时使用了 行 列 固定表头 错位的大小就是滚动条的高度

还有一个问题就是 table 的 height max-height 值 无法使用string 去指向某个css

我看你们的代码 是直接读的数字 然后加上了 'px'

**Comment by liril-net** [comment]
你是想指定什么样的值？`inherit`？

**Comment by mcdongWang** [comment]
@liril-net  指定一个class  让组件通过clss去读啊  我想用calc()

**Comment by wooodchen** [comment]
遇到相同的问题。

测试了下，当表格宽度刚好大于父容器一个竖向滚动条的宽度（好像都是17px）内时，会出现这个问题。

目前自己的解决方法：自定义了一个指令，来判断二者的宽度，当小于这个值时，强制将表格宽度减少一个值，可以暂时解决这个问题。

**Comment by yangehappy** [comment]
@wooodchen 你好 方便公布下代码吗 现在遇到了同样的问题 十分感谢 祝工作愉快

**Comment by geraldlrh** [comment]
没人解决？

**Comment by phcloud** [comment]
ivan403704409 的demo代码现在看已经是正常了的
然而加上show-summary之后，最后几行显示就错位了 https://jsfiddle.net/pointhalo/gkky2vy4/

**Comment by furybean** [comment]
重现的例子更新到 2.1.0 版本版本后已经无法重现： https://jsfiddle.net/dqjsk1y2/3/

**Comment by furybean** [comment]
先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。

**Comment by llukang** [comment]
现在2.7.2版本依然哟这个问题呢，有解决方案了吗？

**Comment by baimifan2017** [comment]
各位老哥，有没有解决方案啊！为这事脑袋都弄疼了

**Comment by yy0608** [comment]
当有fixed属性时，渲染了2个table，设置第二个table水平滚动条就好了
.el-table__body-wrapper.is-scrolling-left + .el-table__fixed-right .el-table__fixed-body-wrapper {
    overflow-x: scroll;
}

**Comment by kaimzhou** [comment]
```js
watch: {
    data() {
      // 对 Table 进行重新布局
      // https://element.eleme.cn/#/zh-CN/component/table#table-methods
      this.$refs.table.doLayout();
    }
  }
```

**Comment by liqiangl** [comment]
2.10.1版本依然有这个问题，使用this.$refs.table.doLayout()依然不能解决问题

**Comment by TY-LIU** [comment]
> 2.10.1版本依然有这个问题，使用this.$refs.table.doLayout()依然不能解决问题

只需要给你的列设定至少一个或一个以上的min-width就解决了，全部都是设置的width并且超出了列表的宽度，就会出现这个问题。看这个：https://jsfiddle.net/6nobuLqv/10/

**Comment by PotCharlesLee** [comment]
> > 2.10.1版本依然有这个问题，使用this.$refs.table.doLayout()依然不能解决问题
> 
> 只需要给你的列设定至少一个或一个以上的min-width就解决了，全部都是设置的width并且超出了列表的宽度，就会出现这个问题。看这个：https://jsfiddle.net/6nobuLqv/10/

之前表格高度是设置为min-height，将min-height修改为height，还有种方法是在数据填充完刷新一下数据让表格重新渲染，目前我就想到这两个方法

**Comment by aimeiyijia** [comment]
估计是各el-table-column的width相加跟屏幕分辨率不匹配的原因，可以设置一列为auto或者不设置宽度。

**Comment by xindiyang** [comment]
就没有解决办法吗

**Comment by azzlzzxz** [comment]
有没有明确的办法啊，以上办法都试过了

**Comment by XiaoWinter** [comment]
找到一个僵硬的办法
`/deep/ .el-table__fixed .cell{
    box-sizing: border-box ;
    max-height: 40px ;
}`

**Comment by PLQin** [comment]
![image](https://user-images.githubusercontent.com/24371471/78626145-77f7bd80-78c0-11ea-8573-dbf635b45a4d.png)

vue 版本： vue2
element 版本： 2.13.0

**Comment by SLL0711** [comment]
vue 2.6.11
element-ui 2.13.2 
试过上述方法，但都无效...
![111](https://user-images.githubusercontent.com/32668092/85137293-888ac380-b273-11ea-8a00-ef2fde957c0b.png)

当启用column 锁定、column宽度自定义时 会出现问题，截图如下

**Comment by SLL0711** [comment]
![image](https://user-images.githubusercontent.com/32668092/85137347-a1937480-b273-11ea-90c6-5d85ba7cbad5.png)

**Comment by passioncsu** [comment]
反正问题还在,  其实稍微调整一下某个列的列宽什么的 就会恢复正常.  最终发现最好用的办法就是setTimeout延迟1秒做个小调整.

**Comment by luojanet** [comment]
方式1： ![image](https://user-images.githubusercontent.com/31914448/86077521-adc2d180-babe-11ea-9162-98d2b0e0c1b6.png)
方式2： :height="tableHeight" 改为:max-height="tableHeight"

**Comment by luojanet** [comment]
方式1： 
![image](https://user-images.githubusercontent.com/31914448/86077701-085c2d80-babf-11ea-9a0f-a440cc04a8e1.png)
方式2：
 :height="tableHeight"改为:max-height="tableHeight"

**Comment by SLL0711** [comment]
HI&nbsp;
方式2尝试后无效


方式1 代码执行放在哪个事件中？或者你是通过定时器循环执行？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"luojanet"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 上午10:47
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"沈丽林"<837316150@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] [Bug Report] 当有一列是fixed时，table显示错位 (#4976)





 
方式1：
 
 方式2：
 :height="tableHeight"改为:max-height="tableHeight"

**Comment by luojanet** [comment]
就放在methods里面，每次请求el-table中数据的时候都会调用执行

**Comment by luojanet** [comment]
就放在methods里面，每次请求el-table中数据的时候都会调用执行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SLL0711"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 晚上9:09
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"luojanet"<1021221052@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] [Bug Report] 当有一列是fixed时，table显示错位 (#4976)





 HI&amp;nbsp; 
 方式2尝试后无效 
 
 
 方式1 代码执行放在哪个事件中？或者你是通过定时器循环执行？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"luojanet"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年6月30日(星期二) 上午10:47 
 收件人:&amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"沈丽林"<837316150@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ElemeFE/element] [Bug Report] 当有一列是fixed时，table显示错位 (#4976) 
 
 
 
 
 
   
 方式1： 
   
  方式2： 
  :height="tableHeight"改为:max-height="tableHeight"

**Comment by fatpandaria** [comment]
没想到这个bug居然这么老了，亲测手动执行`this.$refs.table.doLayout()`方法有效；

**Comment by zhengmiaohua** [comment]
> 而且有时候列神奇的就第一列到最后去了

今天我遇到了这个问题

**Comment by anrgct** [comment]
我在keep-alive组件activated时调用了一下就好了
`
activated(){
     this.$refs.table.doLayout()
 }
`

**Comment by gezeyou** [comment]
测试了以上的，this.$refs.table.doLayout()和settimeout，依旧没用。element版本为2.13.2

**Comment by elvis-fxw** [comment]
还没人解决吗？我也找不到有用的办法

**Comment by gezeyou** [comment]
> 还没人解决吗？我也找不到有用的办法

我目前用最笨的方案就是动态渲染就不采用固定列，采用固定列就不用动态渲染，而是每个列设置宽度

**Comment by whelamc** [comment]
`  ::v-deep .el-table__fixed-body-wrapper .el-table__row td .cell span {
    white-space:nowrap;
  }`

**Comment by 0x3ff** [comment]
目前看到的问题是因为el-table__fixed-right-patch这里默认给了48px的高度，但是浮动列的默认高度为53px，就导致错位了，解决办法是设置class-name属性让他统一成53px

**Comment by whelamc** [comment]
> 目前看到的问题是因为el-table__fixed-right-patch这里默认给了48px的高度，但是浮动列的默认高度为53px，就导致错位了，解决办法是给浮动列设置class-name属性让他统一patch成53px

不得行,应该设置不让内容换行

**Comment by 0x3ff** [comment]
是的，后面使用的时候发现内容换行后浮动列没有自适应，应该是没有对应的监听，项目太赶没工夫找，只能将就去掉浮动了

Whelam ***@***.***> 于2021年11月11日周四 13:16写道：

**Comment by yy0608** [comment]
来邮收到，谢谢！高*谊  (自动回复邮件)

**Comment by jzyds** [comment]
mark

**Comment by yy0608** [comment]
来邮收到，谢谢！高*谊  (自动回复邮件)

**Comment by Supposer** [comment]
版本 2.15.7 问题还没解决, 
表格设置右侧固定列，当页面足够宽时，此时没有触发固定列；
当切换菜单，再重新切换该页面时，固定列错位。

**Comment by xgChange** [comment]
> 2.15.1版本。
我这边的需求是要动态设置表格高度，并且是固定表头和固定列。
最初显示的时候发现列没有对齐。所以就通过css，分别设置 fixed column那个表格的td， 和非固定table的td。如下面

```css
// 非固定列的table
    ::v-deep .el-table__body-wrapper {
      overflow-x: auto;
      overflow-y: auto;
      table {
        td {
          padding-top: 4px !important;
          padding-bottom: 4px !important;
          height: 48px !important;
          padding-left: 10px !important;
          padding-right: 10px !important;
        }
      }
    }
// 固定列的 table
    ::v-deep .el-table__fixed {
      bottom: 8px !important;
      &::before {
        height: 0;
      }
      table {
        td {
          padding-top: 4px !important;
          padding-bottom: 4px !important;
          height: 48px !important;
          padding-left: 10px !important;
        }
      }
    }
```

> 然后当滚动条滚到底部的时候，也发现两边的表格错位。

 因为我改了滚动条的样式，滚动条的高度我给了 scrollHeight -> 8
 主要是在 重新render的时候，设置 ".el-table__body-wrapper的高度" 等于 ".el-table__fixed-body-wrapper" 的高度
```javascript
 // 基于element table 封装了一层 fixedTable组件
{
    methods: {
        resetTableHeight() {
            const TableDom = elTableDom?.querySelector('.el-table')
            if (TableDom) {
                this.$nextTick(() => {
                  if (this.isFixedColumn) {
                    setTimeout(() => {
                      const wrapperDomHeight =
                        elTableDom.querySelector('.el-table__body-wrapper')?.getBoundingClientRect()
                          .height || 0
                      const fixedColumnDom = elTableDom.querySelector('.el-table__fixed-body-wrapper')
                      fixedColumnDom.style.height = `${wrapperDomHeight - this.scrollHeight}px` // scrollHeight 是滚动条高度，看情况设置
                    })
                  }
                })
            }
        }
    },
    // 分别在created、 watch -> data 、resizeEvent的时候调用就好了
    watch: {
      data: {
        handler(v) {
          this.$nextTick(() => {
            this.resetTableHeight()
          })
        },
        deep: true,
      },
    },
    created() {
      this.$nextTick(() => {
        this.resetTableHeight()
      })
    }
}
```

**Comment by yy0608** [comment]
来邮收到，谢谢！高*谊  (自动回复邮件)

**Comment by Lin3943** [comment]
fixed以后，fixed部分的字段固定了，不会跟随下拉滚动，导致错位，这个问题目前只能动态重新计算fixed的列高跟随滚动，否则只用doLayout（）和固定样式也是没法实现的吧

**Comment by yy0608** [comment]
来邮收到，谢谢！高*谊  (自动回复邮件)

**Comment by FTZANKE** [comment]
我这个可以吗？我的项目面解决了
```css
  ::v-deep .el-table {
    border: none;

    &.el-table--scrollable-y .el-table__body-wrapper::-webkit-scrollbar {
      width: 0;
    }

    .el-table__body-wrapper {
      &::-webkit-scrollbar {
        height: 5px;
      }

      &::-webkit-scrollbar-thumb {
        &:hover {
          background: #409eff;
        }
      }
    }

    .el-table__fixed-body-wrapper .el-table__body {
      padding-bottom: 5px;
    }
  }
```

**Comment by FTZANKE** [comment]
> ### 元素界面版
> 1.3.3
> 
> ### 操作系统/浏览器版本
> mac os sierra/chrome 58.0.3029.110（64位）
> 
> ### 版本
> 2.3.3
> 
> ### 转载链接
> https://jsfiddle.net/dqjsk1y2/
> 
> ### 重新发现步骤
> https://jsfiddle.net/dqjsk1y2/
> 
> 往下拉滚动条，到后面的数据，表格上下面会有错位
> 
> ### 什么是预期？
> 表格每行都对齐
> 
> ### 到底发生了什么？
> 往下拉滚动条，到后面的数据，表格上下面会有错位
> 
> ![](https://raw.githubusercontent.com/ivan403704409/bug-img/master/element-ui-table-bug1.png)



> ### Element UI version
> 1.3.3
> 
> ### OS/Browsers version
> mac os sierra/chrome 58.0.3029.110 (64-bit)
> 
> ### Vue version
> 2.3.3
> 
> ### Reproduction Link
> https://jsfiddle.net/dqjsk1y2/
> 
> ### Steps to reproduce
> https://jsfiddle.net/dqjsk1y2/
> 
> 往下拉滚动条，到后面的数据，表格上下会有错位
> 
> ### What is Expected?
> 表格每行都对齐
> 
> ### What is actually happening?
> 往下拉滚动条，到后面的数据，表格上下会有错位
> 
> ![](https://raw.githubusercontent.com/ivan403704409/bug-img/master/element-ui-table-bug1.png)

https://github.com/ElemeFE/element/issues/4976#issuecomment-1345907744

**Comment by WangNingning1994** [comment]
Any update？

**Comment by yy0608** [comment]
来邮收到，谢谢！高*谊  (自动回复邮件)

**Comment by Gaays** [comment]
@FTZANKE 给了我一些灵感，实现了一个相对通用一些的解决方法

原因：FTZANKE方法的问题是只有数据数量未超出表格高度，没有出现scroll-y时有效，在出现scroll-y时el-table__body的高度是大于外层el-table__body-wrapper的，设置el-table__body的padding-bottom是没有用的，不会撑起两侧的fix table高度。

解决方法：
我们可以给 `el-table__fixed` 和 `el-table__fixed-right` 设置padding-bottom，大小与滚动条大小一致，然后再修改内部的 `el-table__fixed-body-wrapper` 将其高度设置为与 `el-table__body-wrapper` 高度一致即可。

解决了： 1.横向滚动条被fixed列遮挡。2.修改过滚动条高度导致fix列高度计算异常，表格滑动到底部，fixed列与普通列错位问题。

详细代码内容如下,我的滚动条设置宽高为9px：
style：
```scss
.el-table__fixed,
  .el-table__fixed-right {
    height: calc(100% - 9px) !important;  
  }

  // 此处修改右侧fix列样式，防止遮挡y轴滚动条
  &.el-table--scrollable-y {
    .el-table__fixed-right {
      &::before {
        background-color: transparent !important;
      }
      right: 9px !important;
    }
    .el-table__fixed-right-patch {
      width: 9px !important;
    }
  }
}
```

js部分，通过获取表格表头高度，与`el-table__fixed` 高度相减即为 `el-table__fixed-body-wrapper` 高度，这里使用ref因为我的表格组件化了，每个页面可能存在多个表格，通过ref单独修改每个表格内的样式：

```js
setFixedBodyHeight() {
  // 获取当前表头高度
  const tableHeaderDom = this.$refs.tableRef.$el.getElementsByClassName(
    'el-table__header-wrapper'
  );
  let tableHeaderHeight = 0;
  if (tableHeaderDom.length > 0) {
    tableHeaderHeight = tableHeaderDom[0].offsetHeight;
    const style = document.createElement('style');
    style.innerHTML = `#${this.tableId}{.el-table__fixed-body-wrapper{height: calc(100% - ${tableHeaderHeight}px) !important;}}`;
    const script = document.querySelector('script');
    script.parentNode.insertBefore(style, script);
  }
},
```

![image](https://user-images.githubusercontent.com/44692140/234754916-66344926-4200-4eab-bd6d-360bafb4b8e0.png)

如果有更好、更优雅的方法，希望可以可以@ 我，如果有什么问题，也希望大家指正
