### ISSUE TITLE
The sizes of the [Feature Request] Pagination component increases with the popper-class setting

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#5120]
### Existing Component
是

### Component Name
pagination

### Description
pagination的size 展开后样式是
```css
.el-select-dropdown__item {
    font-size: 14px;
    padding: 8px 10px;
    position: relative;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    color: #48576a;
    height: 36px;
    line-height: 1.5;
    box-sizing: border-box;
    cursor: pointer
}
```

和
```css
.el-pagination .el-select .el-input input {
    padding-right: 25px;
    border-radius: 2px;
    height: 28px
}
```
的字体大小，容器高度不一致，希望Pagination 组件 能增加一个对sizes的select-dropdown的样式设置
