### ISSUE TITLE
The [Bug Report] select selector is in the disabled state, and the cursor style in the small triangle is still pointer

### ISSUE THREAD

**Issue by magicianShiro** [ElemeFE/element#6139]
### Element UI version
1.4.1

### OS/Browsers version
windows7/chrome59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/kbuuok0m/](https://jsfiddle.net/kbuuok0m/)

### Steps to reproduce
将鼠标移至 禁用的下拉框 的 小三角位置

### What is Expected?
小三角的 cursor 样式 显示为 not-allowed

### What is actually happening?
小三角的 cursor 样式 显示为 pointer

**Comment by Leopoldthecoder** [comment]
Fixed in #6151

**Comment by fritx** [comment]
+99999
fixed \*\*\*!

https://github.com/twbs/bootstrap/issues/16088#issuecomment-198469528

I had to append:

```scss
// 来个粗暴点的 测试要求 disabled手型都统一not-allowed
// https://github.com/twbs/bootstrap/issues/16088
[disabled], .is-disabled {
  cursor: not-allowed;
  * {
    pointer-events: none;
  }
}
```
