### ISSUE TITLE
[Bug Report], when the width of the el-table container is determined by el-table, bug appears

### ISSUE THREAD

**Issue by FrankFang** [ElemeFE/element#6670]
### Element UI version
1.4.2

### OS/Browsers version
MacOS / Chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/FrankFang/pen/VzdoGY](https://codepen.io/FrankFang/pen/VzdoGY)

### Steps to reproduce
当 el-table 容器的宽度是由 el-table 决定时，会出现 bug

### What is Expected?
table 不应该有这样的「动画」

### What is actually happening?
table 出现了烦人的「动画」

**Comment by FrankFang** [comment]
@element-bot  Thanks for your translation!

**Comment by openks** [comment]
这个是不是跟你的布局有关的？@FrankFang 你看下这个是否是你需要的
```css
.flex {
  display: flex;
  flex:1;
  border: 2px solid black;
  padding: 5px;
}
```
https://codepen.io/openks/pen/mMjbPm
