### ISSUE TITLE
[Bug Report] Transfer - Option's labels line-height wrong

### ISSUE THREAD

**Issue by Elfayer** [ElemeFE/element#7667]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
Windows 7 / Chrome 61

### Vue version
2.5.2

### Reproduction Link
[http://element.eleme.io/2.0/#/en-US/component/transfer](http://element.eleme.io/2.0/#/en-US/component/transfer)

### Steps to reproduce
Just go on the Transfer documentation.

### What is Expected?
Options labels to be aligned with its checkbox.

### What is actually happening?
Options labels is too high.

### Fix

Labels options are too high compare to the checkbox. Due to wrong styling:
```css
.el-checkbox__label {
  display: inline-block;
  padding-left: 10px;
  line-height: 19px; /* remove this line */
  font-size: 14px;
}
```
