### ISSUE TITLE
 [Bug Report]  The select of inline form is shifted 1px upward when there is Chinese character in selected el-option's label

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#8073]
### Element UI version
2.0.3

### OS/Browsers version
Windows 10 / Chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/hpep6f3b/](https://jsfiddle.net/hpep6f3b/)

### Steps to reproduce
查看demo
仅当`el-option`的`label`中存在汉字时才会发生偏移

### What is Expected?
inline form中的`select`和`input`水平居中

### What is actually happening?
select向上偏移了1px

另：文档中的select的size属性应更新为medium/small/mini，现为large/small/mini

**Comment by Leopoldthecoder** [comment]
Mac 上似乎没有这个问题，麻烦确认下添加以下 CSS 是否能解决：
```css
.el-select {
  display: block;
}
```

**Comment by troy351** [comment]
@Leopoldthecoder 问题仍然存在，当同时存在中文和英文的选项时，选择英文选项是正常的，选择中文选项会导致select上移1px

**Comment by troy351** [comment]
经过测试，在Windows上，Chrome+IE11存在这个bug，Edge+Firefox不存在
一种临时解决方法使用以下css覆盖原有样式
```css
.el-form--inline .el-form-item__content {
    vertical-align: middle;
    line-height: normal;
}
```

但进一步找到了其他问题：
demo: [https://jsfiddle.net/swuzxtbo/](https://jsfiddle.net/swuzxtbo/)
下拉选择框，选中中文“区域二”时，仍然会导致下方的input下移1px，而且按钮的文字在拉下框出现的过程中会出现模糊。

以下是详细测试结果（浏览器均为最新版）：
Windows+Edge: 不偏移+不模糊
Windows+Chrome：偏移+模糊
Windows+Firefox：不便宜+不模糊
macOS+Safari ：不偏移+模糊
macOS+Chrome：不偏移+不模糊
