### ISSUE TITLE
[Feature Request] Please offer an entry to change the width of el-menu-collapse.

### ISSUE THREAD

**Issue by chenxxzhe** [ElemeFE/element#8802]
### Existing Component
是

### Component Name
el-menu

### Description
I want the set the menu--collapse 36px width with expand/collapse transition. But now el-menu--collapse is fixed in 64px which means the width transition less than 64px wouldn't work.

Could you offer an entry to change the width of menu--collapse ?
Or other methods could solve my problem

Here is my CSS:
```css
  // 让el-menu展开流畅的关键样式
  .el-menu:not(.el-menu--collapse) {
    width: 200px;
  }
  .el-menu {
    width: 36px;
   }
```
