### ISSUE TITLE
[Bug Report] Anchor with el-button class in el-input do not have some css rules

### ISSUE THREAD

**Issue by AlexRadch** [ElemeFE/element#9079]
### Element UI version
2.0.9

### OS/Browsers version
Any

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/2fk23b1j/4/](https://jsfiddle.net/2fk23b1j/4/)

### Steps to reproduce
Create el-input with button and anchor with "el-button" style. The styled anchor will not have some css rules. See https://jsfiddle.net/2fk23b1j/4/

### What is Expected?
Anchor that looks like el-button.

### What is actually happening?
Styled anchor does not have some css rulles.

To fix this change styles in `input.scss` file from
```scss
    button.el-button, /* this line will be changed */
    div.el-select .el-input__inner,
    div.el-select:hover .el-input__inner {
      border-color: transparent;
      background-color: transparent;
      color: inherit;
      border-top: 0;
      border-bottom: 0;
    }
```
to
```scss
    .el-button, /* this line is changed */
    div.el-select .el-input__inner,
    div.el-select:hover .el-input__inner {
      border-color: transparent;
      background-color: transparent;
      color: inherit;
      border-top: 0;
      border-bottom: 0;
    }
```
