### ISSUE TITLE
[Feature Request] Better apareance to Menu

### ISSUE THREAD

**Issue by jbsoftbr** [ElemeFE/element#9152]
### Existing Component
Yes

### Component Name
el-menu

### Description
I created this CSS to do a menu with gradient menu parent , and submen flat, I think this could be added as a new heme, or could help to do a new theme.

```CSS
ul[class="el-menu-vertical-demo"] {
    line-height: 1 !important;
    vertical-align: top !important;
    
    font-family:Tahoma, sans-serif !important;
    font-weight:normal !important;
    font-size:12px !important;
    background:#3f4348 !important;
    color:black !important;

}

ul[class="el-menu-vertical-demo"] {
    text-decoration: none !important;
}

ul[class="el-menu-vertical-demo"] div {
    display: block !important;
    font-weight: bold !important;
    border-top:1px groove #878e98 !important;
    border-bottom:1px solid #33373d !important;
    color: #fff !important;
    letter-spacing: 0.09em !important;
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#575e63), to(#3f4347)) !important;
    background: -webkit-linear-gradient(top, #575e63, #3f4347) !important;
    background: -moz-linear-gradient(top, #575e63, #3f4347) !important;
    background: -ms-linear-gradient(top, #575e63, #3f4347) !important;
    background: -o-linear-gradient(top, #575e63, #3f4347) !important;
}

ul[class="el-menu-vertical-demo"] div:focus, ul[class="el-menu-vertical-demo"] div:hover {
    background: #566f82 !important; /* fallback colour */
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#527a7a), to(#293d3d)) !important;
    background: -webkit-linear-gradient(top, #527a7a, #293d3d) !important;
    background: -moz-linear-gradient(top, #527a7a, #293d3d) !important;
    background: -ms-linear-gradient(top, #527a7a, #293d3d) !important;
    background: -o-linear-gradient(top, #527a7a, #293d3d) !important;
}

ul[class="el-menu-vertical-demo"] > div[class="el-submenu__title"] {
    display: block !important;
    font-weight: bold !important;
    border-top:1px groove #878e98 !important;
    border-bottom:1px solid #33373d !important;
    color: #fff !important;
    letter-spacing: 0.09em !important;
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#575e63), to(#3f4347)) !important;
    background: -webkit-linear-gradient(top, gray,black ) !important;
    background: -moz-linear-gradient(top, gray, black) !important;
    background: -ms-linear-gradient(top, gray, black) !important;
    background: -o-linear-gradient(top, gray, black) !important;
    vertical-align: text-top !important;
}

ul[class="el-menu-vertical-demo"] > ol, ul[class="el-menu-vertical-demo"] > ul {
    list-style: none !important;
}

.el-menu-item , div[class="el-submenu__title"] {
    vertical-align: text-top !important;
}


.el-submenu {
    background-color: white;
}

.el-menu-item:hover, .el-submenu .el-menu-item:hover, .el-submenu .el-menu-item:hover, .el-submenu.is-active .el-submenu__title:hover {
    background-color: #262626 !important;
    font-weight: bold;
}
```
