### ISSUE TITLE
[Feature Request] How to add third party icons like font-awesome 5

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/element#9268]
### Existing Component
Yes

### Component Name
icon

### Description
There was description on how to add third party icon in FAQ, but it was removed.
The code below doesn't work with font-awesome 5:
```css

@font-face {
  font-family: Font Awesome 5;
  font-style: normal;
  font-weight: 400;
  src: url(../../node_modules/@fortawesome/fontawesome-free-webfonts/webfonts/fa-regular-400.eot);
}

i[class^="el-icon-fa"], i[class*=" el-icon-fa"] {
  font-family:"Font Awesome 5" !important;
  display: inline-block;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  vertical-align: baseline !important;
}

$fa-font-path: "../../node_modules/@fortawesome/fontawesome-free-webfonts/webfonts/";
$fa-css-prefix: "el-icon-fa";

@import "../../node_modules/@fortawesome/fontawesome-free-webfonts/scss/fontawesome.scss";
```
