### ISSUE TITLE
How can the Z-index of [Feature Request] MessageBox be larger than that of loading?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9447]
### Existing Component
是

### Component Name
MessageBox

### Description
MessageBox的z-index如何设置比loading的要大呢？

**Comment by Leopoldthecoder** [comment]
```css
.el-loading-mask {
  z-index: 1000;
}
```
