### ISSUE TITLE
关于新版本Loading 加载问题

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#965]
### ElementUI version

1.0.0
### What is actually happening?
发现更新到1.0.0版本  loading过程中，遮蔽层的颜色是白，官网的例子也是http://element.eleme.io/#/component/loading
怎么改成之前的那种呢，黑灰的，不改源码的前提

**Comment by Leopoldthecoder** [comment]
正式版更新了 Loading 的视觉，只提供白色背景。

目前想要改成之前的颜色的话，可能只能通过 `!important` 来做：
```CSS
.el-loading-mask {
  background-color: rgba(0, 0, 0, .7) !important;
}
```

最晚 1.1 版本中会增加一个 Loading 服务，提供更大限度的自定义。
