### ISSUE TITLE
[Feature Request] With date time picker i cant set time intervals like i would with the date picker

### ISSUE THREAD

**Issue by samkerm** [ElemeFE/element#9982]
### Existing Component
Yes

### Component Name
DateTimePicker

### Description
With the TimePicker i can pass in an option like: 
"{
    start: '08:30',
    step: '00:15',
    end: '18:30'
  }" 
to set start time and end time with the time interval, but with DateTimePicker i dont have that attribute.

**Comment by wacky6** [comment]
Sorry. That's for TimeSelect

**Comment by flrnt** [comment]
@samkerm a workaround could be to hide list item with css ?
```scss
.el-time-spinner__wrapper.el-scrollbar:nth-child(2) {
  .el-scrollbar__view.el-time-spinner__list {
    .el-time-spinner__item {
        display: none;
      &:nth-child(15n+1) {
        display: block;
      }
    }
  }
}
```
